# YAML Workflow syntax for GitHub Actions
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Cypress

on: [push]
# on: [push, pull_request]

jobs:
    Cypress:
        # runs-on: ubuntu-16.04
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "10.x"
            - run: npm run ci:cypress
            # - run: cd client/ && npm run ci:cypress

