# YAML Workflow syntax for GitHub Actions
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Cypress
on: [push]
jobs:
  Cypress:
      runs-on: ubuntu-16.04
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v1
            with:
                node-version: "10.x"
          - uses: cypress-io/github-action@v1
            with:
              start: npm start
              working-directory: client
              wait-on: 'http://localhost:4200'
