name: Cypress

on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: '10.x'
#       - run: npm run test:cypress
#     name: Cypress

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: npm install / start servers
        run: |
          npm ci
          npm run start & npx wait-on http://localhost:3000
#         env:
#           CI: true
      - name: Run Cypress
        run: |
          npx cypress run
        env:
          CI: true

#     - name: Checkout
#       uses: actions/checkout@v1
#     - name: Start server in the background
#       run: npm install && npm run start &
#     - name: Install Cypress and run tests
#       uses: cypress-io/github-action@v1
#       with:
#         working-directory: client
    # - name: Cypress run
    #   uses: cypress-io/github-action@v1
    #   with:
    #     # build: npm run build
    #     start: npm run start
    #     # working-directory: client
    #     wait-on: http://localhost:4200
